services:
  - type: web
    name: telegram-forwarder
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: API_ID
        value: "Sizning_API_ID"
      - key: API_HASH
        value: "Sizning_API_HASH"
      - key: SESSION_STRING
        value: "Sizning_SESSION_STRING"
      - key: SOURCE_CHAT
        value: "tuztuzttt"
      - key: TARGET_CHAT
        value: "eltuzar_livee"
      - key: PORT
        value: "8080"
